import {
  Album,
  Anchor,
  Archive,
  AudioWaveform,
  Bird,
  Book,
  BookMarked,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Briefcase,
  Cake,
  Camera,
  Car,
  Cast,
  Castle,
  Cat,
  ChefHat,
  CirclePlay,
  Clapperboard,
  Code,
  Coins,
  Crown,
  Dices,
  Disc3,
  DiscAlbum,
  Dog,
  Drama,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Gamepad2,
  Ghost,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Image,
  Joystick,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  ListVideo,
  // `Map` do Lucide sombrearia o `Map` global do JS — e este projeto usa
  // `new Map()` de verdade (`use-media-type-map.ts`). O alias é obrigatório,
  // não estilo.
  Map as MapIcon,
  MapPin,
  MessageCircle,
  MessageSquare,
  Mic,
  MicSignal,
  Monitor,
  MonitorPlay,
  Mountain,
  Music,
  Newspaper,
  Package,
  Palette,
  Piano,
  Plane,
  Play,
  Popcorn,
  Puzzle,
  Radio,
  Rocket,
  Rss,
  Sailboat,
  Scale,
  Scroll,
  Shapes,
  Shield,
  Shirt,
  Skull,
  Smartphone,
  Sparkles,
  Speaker,
  SquarePlay,
  Star,
  Swords,
  Tag,
  Target,
  Tent,
  Terminal,
  Theater,
  Ticket,
  TramFront,
  Trees,
  Trophy,
  Tv,
  Utensils,
  VenetianMask,
  Video,
  Zap,
} from 'lucide-react'
import type { IconName } from '@/domain/media-type'

type LucideIcon = typeof BookOpen

/**
 * O acervo de 94 glifos, ligando o NOME que vem do dado ao componente.
 *
 * **Por que o mapa é escrito aqui, se a lista mora no servidor.** Não dá pra
 * resolver um import por string sem perder o tree-shaking: `import * as icons`
 * traria os ~2000 do Lucide pro bundle de um app que roda self-hosted, sem CDN.
 * Import nomeado é a única forma de trazer só o que se usa.
 *
 * **O que impede as duas cópias de divergirem é o COMPILADOR, não disciplina.**
 * `Record<IconName, LucideIcon>` exige que este mapa cubra exatamente o `z.enum`
 * do contrato: glifo novo no servidor que não seja importado aqui **não
 * compila**. É o mais perto de "nunca escrever dos dois lados" (brief, 3.7) que
 * um mapa de imports permite chegar.
 */
export const ICON_SET: Record<IconName, LucideIcon> = {
  clapperboard: Clapperboard,
  film: Film,
  monitor: Monitor,
  'monitor-play': MonitorPlay,
  tv: Tv,
  video: Video,
  play: Play,
  'circle-play': CirclePlay,
  'square-play': SquarePlay,
  'list-video': ListVideo,
  cast: Cast,
  camera: Camera,
  theater: Theater,
  drama: Drama,
  'venetian-mask': VenetianMask,
  ticket: Ticket,
  popcorn: Popcorn,
  sparkles: Sparkles,
  ghost: Ghost,
  castle: Castle,
  crown: Crown,
  skull: Skull,
  flame: Flame,
  book: Book,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  bookmark: Bookmark,
  library: Library,
  newspaper: Newspaper,
  scroll: Scroll,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'gamepad-2': Gamepad2,
  joystick: Joystick,
  dices: Dices,
  puzzle: Puzzle,
  swords: Swords,
  shield: Shield,
  target: Target,
  trophy: Trophy,
  headphones: Headphones,
  music: Music,
  'disc-3': Disc3,
  'disc-album': DiscAlbum,
  album: Album,
  mic: Mic,
  'mic-signal': MicSignal,
  radio: Radio,
  'audio-waveform': AudioWaveform,
  speaker: Speaker,
  piano: Piano,
  palette: Palette,
  image: Image,
  rss: Rss,
  globe: Globe,
  code: Code,
  terminal: Terminal,
  bot: Bot,
  smartphone: Smartphone,
  'graduation-cap': GraduationCap,
  lightbulb: Lightbulb,
  'flask-conical': FlaskConical,
  scale: Scale,
  map: MapIcon,
  'map-pin': MapPin,
  mountain: Mountain,
  trees: Trees,
  leaf: Leaf,
  tent: Tent,
  sailboat: Sailboat,
  anchor: Anchor,
  plane: Plane,
  car: Car,
  'tram-front': TramFront,
  'chef-hat': ChefHat,
  utensils: Utensils,
  cake: Cake,
  shirt: Shirt,
  briefcase: Briefcase,
  coins: Coins,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  heart: Heart,
  star: Star,
  flag: Flag,
  rocket: Rocket,
  zap: Zap,
  folder: Folder,
  archive: Archive,
  package: Package,
  layers: Layers,
  box: Box,
  tag: Tag,
}

/**
 * O glifo genérico de quem não achou.
 *
 * Ele existe porque o servidor devolve `icon` como STRING na leitura, e não
 * como o enum: um banco semeado por uma versão mais nova do produto pode ter
 * glifo que este build não conhece. Cair num genérico é melhor que renderizar
 * nada — que foi exatamente o defeito silencioso que abrir o enum criou.
 */
export const FALLBACK_ICON: LucideIcon = Shapes

export function iconFor(name: string): LucideIcon {
  return ICON_SET[name as IconName] ?? FALLBACK_ICON
}
