/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryEntryIdRouteImport } from './routes/library.$entryId'
import { Route as PilesIndexRouteImport } from './routes/piles.index'
import { Route as PilesPileIdRouteImport } from './routes/piles.$pileId'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as SettingsExportRouteImport } from './routes/settings.export'
import { Route as SettingsImportRouteImport } from './routes/settings.import'
import { Route as SettingsMediaTypesRouteImport } from './routes/settings.media-types'
import { Route as SettingsNetworkRouteImport } from './routes/settings.network'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as SettingsUpdatesRouteImport } from './routes/settings.updates'
import { Route as SearchProviderExternalIdRouteImport } from './routes/search.$provider.$externalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryEntryIdRoute = LibraryEntryIdRouteImport.update({
  id: '/library/$entryId',
  path: '/library/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PilesIndexRoute = PilesIndexRouteImport.update({
  id: '/piles/',
  path: '/piles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilesPileIdRoute = PilesPileIdRouteImport.update({
  id: '/piles/$pileId',
  path: '/piles/$pileId',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/settings/export',
  path: '/settings/export',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/settings/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMediaTypesRoute = SettingsMediaTypesRouteImport.update({
  id: '/settings/media-types',
  path: '/settings/media-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/settings/network',
  path: '/settings/network',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/settings/storage',
  path: '/settings/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUpdatesRoute = SettingsUpdatesRouteImport.update({
  id: '/settings/updates',
  path: '/settings/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchProviderExternalIdRoute =
  SearchProviderExternalIdRouteImport.update({
    id: '/search/$provider/$externalId',
    path: '/search/$provider/$externalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/setup': typeof SetupRoute
  '/library/$entryId': typeof LibraryEntryIdRoute
  '/piles/$pileId': typeof PilesPileIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/media-types': typeof SettingsMediaTypesRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/library/': typeof LibraryIndexRoute
  '/piles/': typeof PilesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/search/$provider/$externalId': typeof SearchProviderExternalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/setup': typeof SetupRoute
  '/library/$entryId': typeof LibraryEntryIdRoute
  '/piles/$pileId': typeof PilesPileIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/media-types': typeof SettingsMediaTypesRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/library': typeof LibraryIndexRoute
  '/piles': typeof PilesIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/search/$provider/$externalId': typeof SearchProviderExternalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/setup': typeof SetupRoute
  '/library/$entryId': typeof LibraryEntryIdRoute
  '/piles/$pileId': typeof PilesPileIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/media-types': typeof SettingsMediaTypesRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/library/': typeof LibraryIndexRoute
  '/piles/': typeof PilesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/search/$provider/$externalId': typeof SearchProviderExternalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/setup'
    | '/library/$entryId'
    | '/piles/$pileId'
    | '/settings/about'
    | '/settings/account'
    | '/settings/export'
    | '/settings/import'
    | '/settings/media-types'
    | '/settings/network'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/storage'
    | '/settings/updates'
    | '/library/'
    | '/piles/'
    | '/search/'
    | '/settings/'
    | '/search/$provider/$externalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/setup'
    | '/library/$entryId'
    | '/piles/$pileId'
    | '/settings/about'
    | '/settings/account'
    | '/settings/export'
    | '/settings/import'
    | '/settings/media-types'
    | '/settings/network'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/storage'
    | '/settings/updates'
    | '/library'
    | '/piles'
    | '/search'
    | '/settings'
    | '/search/$provider/$externalId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notifications'
    | '/setup'
    | '/library/$entryId'
    | '/piles/$pileId'
    | '/settings/about'
    | '/settings/account'
    | '/settings/export'
    | '/settings/import'
    | '/settings/media-types'
    | '/settings/network'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/storage'
    | '/settings/updates'
    | '/library/'
    | '/piles/'
    | '/search/'
    | '/settings/'
    | '/search/$provider/$externalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SetupRoute: typeof SetupRoute
  LibraryEntryIdRoute: typeof LibraryEntryIdRoute
  PilesPileIdRoute: typeof PilesPileIdRoute
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsMediaTypesRoute: typeof SettingsMediaTypesRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsUpdatesRoute: typeof SettingsUpdatesRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PilesIndexRoute: typeof PilesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SearchProviderExternalIdRoute: typeof SearchProviderExternalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$entryId': {
      id: '/library/$entryId'
      path: '/library/$entryId'
      fullPath: '/library/$entryId'
      preLoaderRoute: typeof LibraryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piles/': {
      id: '/piles/'
      path: '/piles'
      fullPath: '/piles/'
      preLoaderRoute: typeof PilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piles/$pileId': {
      id: '/piles/$pileId'
      path: '/piles/$pileId'
      fullPath: '/piles/$pileId'
      preLoaderRoute: typeof PilesPileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/settings/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/media-types': {
      id: '/settings/media-types'
      path: '/settings/media-types'
      fullPath: '/settings/media-types'
      preLoaderRoute: typeof SettingsMediaTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/settings/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/settings/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/updates': {
      id: '/settings/updates'
      path: '/settings/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof SettingsUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$provider/$externalId': {
      id: '/search/$provider/$externalId'
      path: '/search/$provider/$externalId'
      fullPath: '/search/$provider/$externalId'
      preLoaderRoute: typeof SearchProviderExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SetupRoute: SetupRoute,
  LibraryEntryIdRoute: LibraryEntryIdRoute,
  PilesPileIdRoute: PilesPileIdRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsMediaTypesRoute: SettingsMediaTypesRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsUpdatesRoute: SettingsUpdatesRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PilesIndexRoute: PilesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SearchProviderExternalIdRoute: SearchProviderExternalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
